# Generated by Django 4.2.16 on 2024-09-05 04:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='pic',
            field=cloudinary.models.CloudinaryField(default='recipes/no_picture.jpg', max_length=255, verbose_name='image'),
        ),
    ]
