# Generated by Django 4.2.16 on 2024-09-05 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_pic_format_recipe_pic_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='pic_format',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='pic_public_id',
        ),
    ]
